theme: minima
title: My page <3
author: Luz Stocalin
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first time creating a page with GitHub. Please be nice :)
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  luzstocalin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
